
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgkpbjnmzxmvjyzjwchf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFna3Biam5tenhtdmp5emp3Y2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDQyMzMsImV4cCI6MjA2MzE4MDIzM30.O7gYIkEltRy_bMniyrQhMNhFmAnGQ2-MDI7jiQGkLFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
