// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvicvevokvgmafyaktjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2aWN2ZXZva3ZnbWFmeWFrdGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NjMzNjQsImV4cCI6MjA2MjMzOTM2NH0.x60hJ0mjkSJh5CEExCx6XRDHw_2Sn4gxq9kFly0fArc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);